services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
